### ISSUE TITLE
New issue in  __init__.py file after a recent commit.

### ISSUE THREAD

**Issue by terrarishabh** [filipporomani/whatsapp-python#47]
This wrapper was working fine until yesterday, but after some recent changes to __init__.py file , i am seeing this error while running my code: 

```
Traceback (most recent call last):
  File "/home/ubuntu/repos/whatsapp/app.py", line 11, in <module>
    from messenger import Messenger
  File "/home/ubuntu/repos/whatsapp/messenger.py", line 11, in <module>
    from charging import Charging
  File "/home/ubuntu/repos/whatsapp/charging.py", line 13, in <module>
    messenger = WhatsApp(os.getenv("TOKEN"),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/repos/whatsapp/venv/lib/python3.12/site-packages/whatsapp/__init__.py", line 44, in __init__
    latest_int = int(latest.replace(".", ""))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '400post1'
```

**Comment by filipporomani** [comment]
Hello! This issue is caused by the version number which contains a string. To fix this, just pass the `update_check=False` argument in the WhatsApp initialization step. 
You might need to update to version 3.3.9 for this to work. 

Sorry for the issue! 
I'll fix it on pypi when I'm home.
Thanks for reporting!

**Comment by filipporomani** [comment]
This is related to #24, what version are you using?

**Comment by filipporomani** [comment]
I'm relasing v4.0.1, which should fix this issue.
